### ISSUE TITLE
com.esotericsoftware.kryo.KryoException

### ISSUE THREAD

**Issue by security08** [OryxProject/oryx#120]
hi:
I start oryx speed but failed,it seem that version of kafka is mismatch between spark and kafka,my cluster is :Spark 1.2.0, Hadoop 2.6.0,  Kafka 0.8.2-beta, Zookeepe 3.4.6,anyone can help?thanks.
the exception is below:

```
2015-01-21 14:24:42,331 INFO  SpeedLayer:126 Starting SparkContext for master yarn-client, interval 10 seconds
2015-01-21 14:24:43,584 INFO  Remoting:74 Starting remoting
2015-01-21 14:24:43,846 INFO  Remoting:74 Remoting started; listening on addresses :[akka.tcp://sparkDriver@hadoop110:56385]
2015-01-21 14:24:45,232 WARN  NativeCodeLoader:62 Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2015-01-21 14:25:07,598 INFO  SpeedLayer:159 Creating message stream from topic
2015-01-21 14:25:08,354 WARN  ZookeeperConsumerConnector:83 [OryxGroup-SpeedLayer-1421821507619_hadoop110-1421821507725-d4b5d71c], no brokers found when trying to rebalance.
2015-01-21 14:25:08,484 INFO  SpeedLayer:198 Waiting for streaming...
2015-01-21 14:25:19,551 WARN  TaskSetManager:71 Lost task 0.0 in stage 2.0 : java.io.IOException: com.esotericsoftware.kryo.KryoException: java.lang.IllegalArgumentException: Can not set final scala.reflect.ClassTag field org.apache.spark.streaming.kafka.KafkaReceiver.evidence$7 to scala.reflect.ClassTag$$anon$1
Serialization trace:
evidence$7 (org.apache.spark.streaming.kafka.KafkaReceiver)
        at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:988)
        at org.apache.spark.rdd.ParallelCollectionPartition.readObject(ParallelCollectionRDD.scala:70)
        at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1893)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
        at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:62)
        at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:87)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:178)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.esotericsoftware.kryo.KryoException: java.lang.IllegalArgumentException: Can not set final scala.reflect.ClassTag field org.apache.spark.streaming.kafka.KafkaReceiver.evidence$7 to scala.reflect.ClassTag$$anon$1
Serialization trace:
evidence$7 (org.apache.spark.streaming.kafka.KafkaReceiver)
        at com.esotericsoftware.kryo.serializers.FieldSerializer$ObjectField.read(FieldSerializer.java:626)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:221)
        at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:729)
        at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:338)
        at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:293)
        at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:729)
        at com.twitter.chill.WrappedArraySerializer.read(WrappedArraySerializer.scala:36)
        at com.twitter.chill.WrappedArraySerializer.read(WrappedArraySerializer.scala:23)
        at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:729)
        at org.apache.spark.serializer.KryoDeserializationStream.readObject(KryoSerializer.scala:142)
        at org.apache.spark.rdd.ParallelCollectionPartition$$anonfun$readObject$1$$anonfun$apply$mcV$sp$2.apply(ParallelCollectionRDD.scala:80)
        at org.apache.spark.rdd.ParallelCollectionPartition$$anonfun$readObject$1$$anonfun$apply$mcV$sp$2.apply(ParallelCollectionRDD.scala:80)
        at org.apache.spark.util.Utils$.deserializeViaNestedStream(Utils.scala:126)
        at org.apache.spark.rdd.ParallelCollectionPartition$$anonfun$readObject$1.apply$mcV$sp(ParallelCollectionRDD.scala:80)
        at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:985)
        ... 19 more
```

and then the job aborted  :

```
Job aborted due to stage failure: Task 0 in stage 4.0 failed 4 times, most recent failure: Lost task 0.3 in stage 4.0 : java.lang.ClassCastException: cannot assign instance of com.cloudera.oryx.lambda.ValueToWritableFunction to field org.apache.spark.api.java.JavaPairRDD$$anonfun$pairFunToScalaFun$1.x$335 of type org.apache.spark.api.java.function.PairFunction in instance of org.apache.spark.api.java.JavaPairRDD$$anonfun$pairFunToScalaFun$1
	at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2083)
	at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1261)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1996)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:62)
	at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:87)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:57)
	at org.apache.spark.scheduler.Task.run(Task.scala:56)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:196)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

Driver stacktrace:

**Comment by srowen** [comment]
Hm, so the root problem isn't version incompatibility, I think. Your setup sounds virtually identical to the current build. It is that something is causing `KafkaRecevier` to be serialized, but it is not serializable. I bet it's being caught in a closure somehow.

Java serialization has a flag `-Dsun.io.serialization.extendeddebuginfo=true` that will print where the reference to the unserializable object came from. It won't work for Kryo and I've hard-coded Kryo as the serializer. However you can try running with `-Dspark.serializer=org.apache.spark.serializer.JavaSerializer`; if I'm not wrong it will override Kryo. Otherwise I can change the code to make this explicitly configurable.

That, plus the flag above, might help pinpoint the problem. However I can separately eyeball the situation and see if I can guess what the problem may be.

**Comment by security08** [comment]
Hi,srowen 
I have followed your advise running with -Dspark.serializer=org.apache.spark.serializer.JavaSerializer when start oryx speed but still failed.the exception is : 
```
2015-01-26 18:51:03,240 INFO  SpeedLayer:126 Starting SparkContext for master yarn-client, interval 10 seconds
2015-01-26 18:51:04,550 INFO  Remoting:74 Starting remoting
2015-01-26 18:51:04,793 INFO  Remoting:74 Remoting started; listening on addresses :[akka.tcp://sparkDriver@hadoop110:38776]
2015-01-26 18:51:05,886 WARN  NativeCodeLoader:62 Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2015-01-26 18:51:30,821 INFO  SpeedLayer:159 Creating message stream from topic
2015-01-26 18:51:32,705 INFO  SpeedLayer:198 Waiting for streaming...

[Stage 0:>                                                         (0 + 0) / 50]
[Stage 0:>                                                        (0 + 10) / 50]
[Stage 0:>                                                        (0 + 12) / 50]
[Stage 0:==============>                                         (13 + 11) / 50]
[Stage 0:======================================>                 (34 + 10) / 50]
[Stage 0:==================================================>      (44 + 6) / 50]
                                                                                

[Stage 0:==================================================>      (44 + 6) / 50]
[Stage 0:======================================================>  (48 + 2) / 50]
[Stage 1:===================================================>     (18 + 2) / 20]
                                                                                
2015-01-26 18:51:42,592 WARN  TaskSetManager:71 Lost task 0.0 in stage 2.0 (TID 70, hadoop111): java.io.IOException: java.lang.ClassCastException: cannot assign instance of org.apache.spark.storage.StorageLevel to field org.apache.spark.streaming.receiver.Receiver.storageLevel of type org.apache.spark.storage.StorageLevel in instance of org.apache.spark.streaming.kafka.KafkaReceiver
	at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:988)
	at org.apache.spark.rdd.ParallelCollectionPartition.readObject(ParallelCollectionRDD.scala:70)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1893)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:62)
	at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:87)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:178)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: cannot assign instance of org.apache.spark.storage.StorageLevel to field org.apache.spark.streaming.receiver.Receiver.storageLevel of type org.apache.spark.storage.StorageLevel in instance of org.apache.spark.streaming.kafka.KafkaReceiver
	at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2083)
	at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1261)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1996)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1706)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1344)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:500)
	at org.apache.spark.rdd.ParallelCollectionPartition$$anonfun$readObject$1.apply$mcV$sp(ParallelCollectionRDD.scala:74)
	at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:985)
	... 19 more

2015-01-26 18:51:42,831 ERROR TaskSetManager:75 Task 0 in stage 2.0 failed 4 times; aborting job
Exception in thread "Thread-45" org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 2.0 failed 4 times, most recent failure: Lost task 0.3 in stage 2.0 (TID 73, hadoop111): java.io.IOException: java.lang.ClassCastException: cannot assign instance of org.apache.spark.storage.StorageLevel to field org.apache.spark.streaming.receiver.Receiver.storageLevel of type org.apache.spark.storage.StorageLevel in instance of org.apache.spark.streaming.kafka.KafkaReceiver
	at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:988)
	at org.apache.spark.rdd.ParallelCollectionPartition.readObject(ParallelCollectionRDD.scala:70)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1893)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:62)
	at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:87)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:178)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassCastException: cannot assign instance of org.apache.spark.storage.StorageLevel to field org.apache.spark.streaming.receiver.Receiver.storageLevel of type org.apache.spark.storage.StorageLevel in instance of org.apache.spark.streaming.kafka.KafkaReceiver
	at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2083)
	at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1261)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1996)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1706)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1344)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:500)
	at org.apache.spark.rdd.ParallelCollectionPartition$$anonfun$readObject$1.apply$mcV$sp(ParallelCollectionRDD.scala:74)
	at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:985)
	... 19 more

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1214)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1203)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1202)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1202)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:696)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:696)
	at scala.Option.foreach(Option.scala:236)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:696)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessActor$$anonfun$receive$2.applyOrElse(DAGScheduler.scala:1420)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessActor.aroundReceive(DAGScheduler.scala:1375)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
2015-01-26 18:55:20,023 WARN  BlockManagerMaster:71 Failed to remove RDD 22 - Ask timed out on [Actor[akka.tcp://sparkExecutor@hadoop121:51622/user/BlockManagerActor1#682285712]] after [30000 ms]}
```
classpath: 
```
/home/hadoop/oryx2/lib/oryx-speed-2.0.0-SNAPSHOT.jar:/usr/local/cloud/hadoop-2.6.0/etc/hadoop/:/usr/local/cloud/hadoop-2.6.0/share/hadoop/common/hadoop-common-2.6.0.jar:/usr/local/cloud/hadoop-2.6.0/share/hadoop/hdfs/hadoop-hdfs-2.6.0.jar:/usr/local/cloud/hadoop-2.6.0/share/hadoop/hdfs/hadoop-hdfs-nfs-2.6.0.jar:/usr/local/cloud/hadoop-2.6.0/share/hadoop/mapreduce/hadoop-mapreduce-client-core-2.6.0.jar:/usr/local/cloud/hadoop-2.6.0/share/hadoop/tools/lib/commons-cli-1.2.jar:/usr/local/cloud/hadoop-2.6.0/share/hadoop/tools/lib/commons-collections-3.2.1.jar:/usr/local/cloud/hadoop-2.6.0/share/hadoop/tools/lib/commons-configuration-1.6.jar:/usr/local/cloud/hadoop-2.6.0/share/hadoop/tools/lib/commons-lang-2.6.jar:/usr/local/cloud/hadoop-2.6.0/share/hadoop/tools/lib/hadoop-auth-2.6.0.jar:/usr/local/cloud/hadoop-2.6.0/share/hadoop/tools/lib/protobuf-java-2.5.0.jar:/usr/local/cloud/hadoop-2.6.0/share/hadoop/tools/lib/zookeeper-3.4.6.jar:/usr/local/cloud/hadoop-2.6.0/share/hadoop/yarn/hadoop-yarn-api-2.6.0.jar:/usr/local/cloud/hadoop-2.6.0/share/hadoop/yarn/hadoop-yarn-client-2.6.0.jar:/usr/local/cloud/hadoop-2.6.0/share/hadoop/yarn/hadoop-yarn-common-2.6.0.jar:/usr/local/cloud/hadoop-2.6.0/share/hadoop/yarn/hadoop-yarn-server-web-proxy-2.6.0.jar:/usr/local/cloud/spark-1.2.0-bin-2.6.0/lib/spark-assembly-1.2.0-hadoop2.6.0.jar:/usr/local/cloud/spark-1.2.0-bin-2.6.0/lib/spark-examples-1.2.0-hadoop2.6.0.jar
```
extra_prop: 
```
-Dspark.yarn.dist.files=/home/hadoop/oryx2/conf/als.conf  -Dspark.jars=/home/hadoop/oryx2/lib/oryx-speed-2.0.0-SNAPSHOT.jar,/usr/local/cloud/spark-1.2.0-bin-2.6.0/lib/spark-assembly-1.2.0-hadoop2.6.0.jar,/usr/local/cloud/spark-1.2.0-bin-2.6.0/lib/spark-examples-1.2.0-hadoop2.6.0.jar  -Dspark.executor.extraJavaOptions="-Dconfig.file=als.conf"
```
oryx configuration:
```
oryx {
    als {
        hyperparams {
            alpha=1
            features=30
            lambda=0.065
        }
        implicit=true
        iterations=10
        no-known-items=false
    }
    batch {
        storage {
            data-dir="hdfs:///input/oryx2/data/"
            key-writable-class="org.apache.hadoop.io.Text"
            message-writable-class="org.apache.hadoop.io.Text"
            model-dir="hdfs:///input/oryx2/model/"
            partitions=8
        }
        streaming {
            block-interval-sec=5
            driver-memory="1g"
            executor-cores=4
            executor-memory="2g"
            generation-interval-sec=300
            master=yarn-client
            num-executors=5
        }
        ui {
            port=8093
        }
        update-class="com.cloudera.oryx.app.mllib.als.ALSUpdate"
    }
    input-schema {
        categorical-features=null
        feature-names=[]
        id-features=[]
        ignored-features=[]
        num-features=0
        numeric-features=null
        target-feature=null
    }
    input-topic {
        broker="s2:9092,s3:9092,s4:9092"
        lock {
            master="s3:2181,s4:2181,s5:2181/kafka"
        }
        message {
            key-class="java.lang.String"
            key-decoder-class="kafka.serializer.StringDecoder"
            message-class="java.lang.String"
            message-decoder-class="kafka.serializer.StringDecoder"
            topic=OryxInput
        }
    }
    kmeans {
        hyperparams {
            k=10
        }
        initialization-strategy="k-means||"
        iterations=30
        runs=1
    }
    ml {
        eval {
            candidates=1
            parallelism=1
            test-fraction=0.1
        }
    }
    rdf {
        hyperparams {
            impurity=entropy
            max-depth=8
            max-split-candidates=100
            min-info-gain-nats=0.001
            min-node-size=16
        }
        num-trees=20
    }
    serving {
        api {
            context-path="/"
            keystore-file=null
            keystore-password=null
            password=null
            port=8093
            read-only=false
            secure-port=443
            user-name=null
        }
        application-resources="com.cloudera.oryx.app.serving,com.cloudera.oryx.app.serving.als"
        model-manager-class="com.cloudera.oryx.app.serving.als.model.ALSServingModelManager"
        no-init-topics=false
    }
    speed {
        model-manager-class="com.cloudera.oryx.app.speed.als.ALSSpeedModelManager"
        streaming {
            block-interval-sec=1
            driver-memory="1g"
            executor-cores=2
            executor-memory="2g"
            generation-interval-sec=10
            master=yarn-client
            num-executors=5
        }
        ui {
            port=8093
        }
    }
    update-topic {
        broker="s2:9092,s3:9092,s4:9092"
        lock {
            master="s3:2181,s4:2181,s5:2181/kafka"
        }
        message {
            decoder-class="kafka.serializer.StringDecoder"
            encoder-class="kafka.serializer.StringEncoder"
            topic=OryxUpdate
        }
    }
}
```

I only start kafka,create topic OryxUpdate and OryxInput, but hasn't put any data to OryxInput yet.
Thanks.

**Comment by srowen** [comment]
Hm. Now I'm back to thinking there is a `ClassLoader` problem here, then. It says it can't assign a `org.apache.spark.storage.StorageLevel` to a `org.apache.spark.storage.StorageLevel`, which doesn't make sense in general. I doubt it is any problem with how you are running. Since development is completing I'm moving towards testing on a real cluster so will soon find out if I see the same problem.

**Comment by security08** [comment]
Sorry , I am a newer to spark and scala.I have server question :
1.why oryx speed still throw exception(exception that assign a org.apache.spark.storage.StorageLevel to a org.apache.spark.storage.StorageLevel) even there are no data in OryxInput , I think speed will do nothing if there are no data in OryxInput.
2.if I not add spark-assembly jar to spark.jars in run.sh,it will throw :java.lang.NoClassDefFoundError: org/apache/spark/Logging ,which are in spark-assembly jar.when I set spark-assembly jar ,it will throw assign a org.apache.spark.storage.StorageLevel to a org.apache.spark.storage.StorageLevel.I saw the run.sh shell has not set spark-assembly jar to spark.jars.
3.I have set spark.yarn.jar=/path/to/spark-assembly jar in spark,but it still upload assembly jar to .sparkStaging in every time I  start speed.I think that it will no upload any more when I set spark.yarn.jar=/path/to/spark-assembly jar.
Thanks for your help!

**Comment by srowen** [comment]
I don't think it's related to processing data or not; it's simply some
error when executing the jobs whether or not there is data.

You can't remove spark-assembly.jar from the classpath for sure. I don't
think this is relevant.

**Comment by security08** [comment]
I haven't  remove spark-assembly.jar from the classpath,I only remove  spark-assembly.jar in spark.jars. Yes,as you say ,now I think maybe there is a ClassLoader problem here.

**Comment by security08** [comment]
The issue is solved by add -Dspark.files.userClassPathFirst=false to run.sh when I start oryx batch or speed,and it will use ExecutorURLClassLoader in Execotor.scala:
```
298   val userClassPathFirst = conf.getBoolean("spark.files.userClassPathFirst", false)
299   userClassPathFirst match {
300     case true => new ChildExecutorURLClassLoader(urls, currentLoader)
301      case false => new ExecutorURLClassLoader(urls, currentLoader)
302   }
```

**Comment by srowen** [comment]
@security08 That's good to know. That does point to a classloader issue indeed. While I understand the problem, I am still not quite clear why it occurs here. It's good to have that as a workaround, and I will likely enable it by default.
