### ISSUE TITLE
Flaky test: RDFSpeedIT probability check

### ISSUE THREAD

**Issue by srowen** [OryxProject/oryx#176]
Seen this twice now; needs to be made more robust:

```
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 51.01 sec <<< FAILURE! - in com.cloudera.oryx.app.speed.rdf.RDFSpeedIT
testRDFSpeedClassification(com.cloudera.oryx.app.speed.rdf.RDFSpeedIT)  Time elapsed: 25.91 sec  <<< FAILURE!
java.lang.AssertionError: 44 should be about 90% of 46
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.cloudera.oryx.app.speed.rdf.RDFSpeedIT.checkProbability(RDFSpeedIT.java:184)
	at com.cloudera.oryx.app.speed.rdf.RDFSpeedIT.testRDFSpeedClassification(RDFSpeedIT.java:168)
```

**Comment by srowen** [comment]
Also:
```
java.lang.AssertionError: 5 should be about 4.5 (~90% of 5)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.cloudera.oryx.app.speed.rdf.RDFSpeedIT.checkProbability(RDFSpeedIT.java:184)
	at com.cloudera.oryx.app.speed.rdf.RDFSpeedIT.testRDFSpeedClassification(RDFSpeedIT.java:171)
```
