### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.spark.api.java.JavaPairRDD.isEmpty()

### ISSUE THREAD

**Issue by thanigaiv** [OryxProject/oryx#197]
When I try to run the ALS example, I get this error on both batch and speed layers. This prevents from running the algorithms on the batches. Any ideas?

Exception in thread "pool-8-thread-4" java.lang.NoSuchMethodError: org.apache.spark.api.java.JavaPairRDD.isEmpty()Z
	at com.cloudera.oryx.lambda.batch.SaveToHDFSFunction.call(SaveToHDFSFunction.java:56)
	at com.cloudera.oryx.lambda.batch.SaveToHDFSFunction.call(SaveToHDFSFunction.java:31)
	at org.apache.spark.streaming.api.java.JavaDStreamLike$$anonfun$foreachRDD$2.apply(JavaDStreamLike.scala:282)
	at org.apache.spark.streaming.api.java.JavaDStreamLike$$anonfun$foreachRDD$2.apply(JavaDStreamLike.scala:282)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply$mcV$sp(ForEachDStream.scala:42)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:40)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:40)
	at scala.util.Try$.apply(Try.scala:161)
	at org.apache.spark.streaming.scheduler.Job.run(Job.scala:32)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply$mcV$sp(JobScheduler.scala:176)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply(JobScheduler.scala:176)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply(JobScheduler.scala:176)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler.run(JobScheduler.scala:175)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by smarthi** [comment]
RDD.isEmpty() was added in Spark 1.3.0, r u running with Spark 1.3.0 ?

**Comment by thanigaiv** [comment]
I'm running with 1.2 - I will try it with 1.3.0

**Comment by smarthi** [comment]
You would see that error with 1.2, RDD.isEmpty() was added in 1.3.0

**Comment by thanigaiv** [comment]
sounds good - the documentation needs to be updated as it says that only Spark 1.2 or later is needed. Also, for CDH users, CDH 5.3 (latest release) only has Spark 1.2 and we need to wait for CDH 5.4 to release to get Spark 1.3

**Comment by smarthi** [comment]
Thanks for the feedback, will update the documentation.

**Comment by srowen** [comment]
The current "alpha 1" release works on Spark 1.2. Yes, the current `master` requires 1.3 and so will the next "alpha 2" release in a month or so.
