### ISSUE TITLE
project compilation failed

### ISSUE THREAD

**Issue by qzuo** [OryxProject/oryx#205]
ExampleScalaBatchLayerUpdate.scala:22: error: object ScalaBatchLayerUpdate is not a member of package com.cloudera.oryx.api.batch
ExampleScalaBatchLayerUpdate.scala:24: error: not found: type ScalaBatchLayerUpdate

**Comment by srowen** [comment]
How did you compile it? were there earlier errors? The build is passing at the moment:
https://travis-ci.org/OryxProject/oryx

**Comment by qzuo** [comment]
I did: git clone https://github.com/OryxProject/oryx
then did: mvn compile
I saw the errors

What I did then is: mvn clean; mvn compile 
Now the compile is okay. 

Do I need to install kafka, hadoop, ... on the machine where I compile the code in order to run: mvn install?

**Comment by srowen** [comment]
No, the build is entirely self-contained and as you can see is passing in several build configurations. You haven't said what the errors are, but I suspect they are local to your environment. I have just tried your exact steps on a new image and have no problems.

**Comment by qzuo** [comment]
This is what I see:

2015-04-14 10:15:56,857 INFO  LocalZKServer:73 Starting Zookeeper on port 59359
2015-04-14 10:15:56,873 INFO  LocalZKServer:81 ZK config: {clientPort=59359, dataDir=/var/folders/m0/gp73bhxn41sfsqffxg4vjfh80000gn/T/LocalZKServer3294950481704845254}
2015-04-14 10:15:57,066 INFO  LocalKafkaBroker:68 Starting Kafka broker on port 59360
2015-04-14 10:15:57,676 FATAL KafkaServer:116 [Kafka Server 8675309], Fatal error during KafkaServer startup. Prepare to shutdown
java.net.UnknownHostException: QZUO-M-P07L: QZUO-M-P07L: nodename nor servname provided, or not known
	at java.net.InetAddress.getLocalHost(InetAddress.java:1473)
	at kafka.server.KafkaHealthcheck.register(KafkaHealthcheck.scala:54)
	at kafka.server.KafkaHealthcheck.startup(KafkaHealthcheck.scala:45)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:124)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:29)
	at com.cloudera.oryx.kafka.util.LocalKafkaBroker.start(LocalKafkaBroker.java:80)
	at com.cloudera.oryx.kafka.util.ProduceConsumeIT.testProduceConsume(ProduceConsumeIT.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.net.UnknownHostException: QZUO-M-P07L: nodename nor servname provided, or not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:901)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1293)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1469)
	... 32 more
2015-04-14 10:15:58,012 FATAL KafkaServerStartable:116 Fatal error during KafkaServerStartable startup. Prepare to shutdown
java.net.UnknownHostException: QZUO-M-P07L: QZUO-M-P07L: nodename nor servname provided, or not known
	at java.net.InetAddress.getLocalHost(InetAddress.java:1473)
	at kafka.server.KafkaHealthcheck.register(KafkaHealthcheck.scala:54)
	at kafka.server.KafkaHealthcheck.startup(KafkaHealthcheck.scala:45)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:124)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:29)
	at com.cloudera.oryx.kafka.util.LocalKafkaBroker.start(LocalKafkaBroker.java:80)
	at com.cloudera.oryx.kafka.util.ProduceConsumeIT.testProduceConsume(ProduceConsumeIT.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: java.net.UnknownHostException: QZUO-M-P07L: nodename nor servname provided, or not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:901)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1293)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1469)
	... 32 more

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Oryx .............................................. SUCCESS [11.873s]
[INFO] API ............................................... SUCCESS [5.915s]
[INFO] Common ............................................ SUCCESS [8.598s]
[INFO] Zookeeper Utilities ............................... SUCCESS [1.551s]
[INFO] Kafka Utilities ................................... FAILURE [4.121s]
[INFO] Lambda ............................................ SKIPPED
[INFO] Lambda Serving .................................... SKIPPED
[INFO] ML ................................................ SKIPPED
[INFO] Apps: API ......................................... SKIPPED
[INFO] Apps: Common ...................................... SKIPPED
[INFO] Apps: Spark MLlib ................................. SKIPPED
[INFO] Apps: Oryx ........................................ SKIPPED
[INFO] Apps: Oryx (Serving) .............................. SKIPPED
[INFO] Example ........................................... SKIPPED
[INFO] Batch Layer ....................................... SKIPPED
[INFO] Speed Layer ....................................... SKIPPED
[INFO] Serving Layer ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 32.798s
[INFO] Finished at: Tue Apr 14 10:15:58 PDT 2015
[INFO] Final Memory: 47M/655M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.18.1:integration-test (default) on project kafka-util: Execution default of goal org.apache.maven.plugins:maven-failsafe-plugin:2.18.1:integration-test failed: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /Users/qzuo/ioe-platform/oryx/framework/kafka-util && /Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home/jre/bin/java -jar /Users/qzuo/ioe-platform/oryx/framework/kafka-util/target/surefire/surefirebooter8519521964556393208.jar /Users/qzuo/ioe-platform/oryx/framework/kafka-util/target/surefire/surefire7580505477419508483tmp /Users/qzuo/ioe-platform/oryx/framework/kafka-util/target/surefire/surefire_03840724979818582976tmp
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :kafka-util

**Comment by srowen** [comment]
Ah, you are running `package` or `install` not `compile`, which runs unit tests and integration tests. Unit tests should always run fine, but integration tests will try to start Kafka locally. The hostname that your machine resolves to isn't valid: QZUO-M-P07L  It's not a problem with the tests, but your environment. Still, just `-DskipTests` if you want to only compile and package the code.

**Comment by qzuo** [comment]
Followed your instruction. It works now. Thanks :+1:
