### ISSUE TITLE
Exception in thread "main" java.lang.IllegalArgumentException: You must specify at least 1 executor! when starting Batch layer

### ISSUE THREAD

**Issue by dsdinter** [OryxProject/oryx#209]
It seems this variable is not initialised in case is missing inside AbstractSparkLayer()

Just adding the below line fixed the exception in my cluster (CDH 5.4 with Kafka 1.3.0):
sparkConf.setIfMissing("spark.dynamicAllocation.minExecutors","1");

There were actually some discussions about similar topic:
https://www.mail-archive.com/user@spark.apache.org/msg26352.html

**Comment by srowen** [comment]
A minimum of 0 should be accepted and this was fixed for 1.3.0. Actually the code doesn't set any value, but that should be OK, I'd imagine. What is the error? You are running `master`?

**Comment by dsdinter** [comment]
That was my assumption, yes I compiled  master branch and using Spark 1.3.0 from CM 5.4.
I can try to set the value to 0 instead:
sparkConf.setIfMissing("spark.dynamicAllocation.minExecutors","0");

**Comment by srowen** [comment]
A minimum of 1 isn't so bad either but I'm curious what the error was?

**Comment by dsdinter** [comment]
There you go:
2015-05-01 12:59:13,166 INFO  BatchLayer:83 Starting Batch Layer 802483597
2015-05-01 12:59:13,166 INFO  AbstractSparkLayer:146 Starting SparkContext for master yarn-client, interval 300 seconds
2015-05-01 12:59:14,027 INFO  Remoting:74 Starting remoting
2015-05-01 12:59:14,185 INFO  Remoting:74 Remoting started; listening on addresses :[akka.tcp://sparkDriver@node4:19469]
2015-05-01 12:59:14,188 INFO  Remoting:74 Remoting now listens on addresses: [akka.tcp://sparkDriver@node4:19469]
2015-05-01 12:59:14,415 INFO  Server:272 jetty-8.y.z-SNAPSHOT
2015-05-01 12:59:14,427 INFO  AbstractConnector:338 Started SocketConnector@0.0.0.0:33609
2015-05-01 12:59:14,511 INFO  Server:272 jetty-8.y.z-SNAPSHOT
2015-05-01 12:59:14,531 INFO  AbstractConnector:338 Started SelectChannelConnector@0.0.0.0:64040
Exception in thread "main" java.lang.IllegalArgumentException: You must specify at least 1 executor!

Usage: org.apache.spark.deploy.yarn.Client [options]
Options:
  --jar JAR_PATH           Path to your application's JAR file (required in yarn-cluster
                           mode)
  --class CLASS_NAME       Name of your application's main class (required)
  --primary-py-file        A main Python file
  --arg ARG                Argument to be passed to your application's main class.
                           Multiple invocations are possible, each will be passed in order.
  --num-executors NUM      Number of executors to start (Default: 2)
  --executor-cores NUM     Number of cores per executor (Default: 1).
  --driver-memory MEM      Memory for driver (e.g. 1000M, 2G) (Default: 512 Mb)
  --driver-cores NUM       Number of cores used by the driver (Default: 1).
  --executor-memory MEM    Memory per executor (e.g. 1000M, 2G) (Default: 1G)
  --name NAME              The name of your application (Default: Spark)
  --queue QUEUE            The hadoop queue to use for allocation requests (Default:
                           'default')
  --addJars jars           Comma separated list of local jars that want SparkContext.addJar
                           to work with.
  --py-files PY_FILES      Comma-separated list of .zip, .egg, or .py files to
                           place on the PYTHONPATH for Python apps.
  --files files            Comma separated list of files to be distributed with the job.
  --archives archives      Comma separated list of archives to be distributed with the job.

        at org.apache.spark.deploy.yarn.ClientArguments.validateArgs(ClientArguments.scala:106)
        at org.apache.spark.deploy.yarn.ClientArguments.<init>(ClientArguments.scala:58)
        at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.start(YarnClientSchedulerBackend.scala:55)
        at org.apache.spark.scheduler.TaskSchedulerImpl.start(TaskSchedulerImpl.scala:141)
        at org.apache.spark.SparkContext.<init>(SparkContext.scala:379)
        at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:61)
        at com.cloudera.oryx.lambda.AbstractSparkLayer.buildStreamingContext(AbstractSparkLayer.java:192)
        at com.cloudera.oryx.lambda.batch.BatchLayer.start(BatchLayer.java:86)
        at com.cloudera.oryx.batch.Main.main(Main.java:34)
2015-05-01 12:59:14,804 ERROR Utils:96 Uncaught exception in thread delete Spark local dirs
java.lang.NullPointerException
        at org.apache.spark.storage.DiskBlockManager.org$apache$spark$storage$DiskBlockManager$$doStop(DiskBlockManager.scala:161)
        at org.apache.spark.storage.DiskBlockManager$$anon$1$$anonfun$run$1.apply$mcV$sp(DiskBlockManager.scala:141)
        at org.apache.spark.storage.DiskBlockManager$$anon$1$$anonfun$run$1.apply(DiskBlockManager.scala:139)
        at org.apache.spark.storage.DiskBlockManager$$anon$1$$anonfun$run$1.apply(DiskBlockManager.scala:139)

**Comment by srowen** [comment]
I think I see what's going on. Yeah, the fastest and most sensible fix is just to always have at least 1 executor.
