### ISSUE TITLE
ALS Example failing 

### ISSUE THREAD

**Issue by moritzschaefer** [OryxProject/oryx#235]
Running the ALS example as described in http://oryx.io/docs/index.html#Trying_the_ALS_Example results in an error in the batch layer:

    2015-07-08 15:15:04,743 ERROR JobScheduler:96 Error running job streaming job 1436361300000 ms.0
    org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 6.0 failed 4 times, most recent failure: Lost task 1.3 in stage 6.0 (TID 70, Lamoda-Dev-Server): java.lang.A
    rrayIndexOutOfBoundsException: 3
            at com.cloudera.oryx.app.batch.mllib.als.ALSUpdate$ParseRatingFn.call(ALSUpdate.java:325)
            at com.cloudera.oryx.app.batch.mllib.als.ALSUpdate$ParseRatingFn.call(ALSUpdate.java:322)
            at org.apache.spark.api.java.JavaPairRDD$$anonfun$pairFunToScalaFun$1.apply(JavaPairRDD.scala:1002)
            at org.apache.spark.api.java.JavaPairRDD$$anonfun$pairFunToScalaFun$1.apply(JavaPairRDD.scala:1002)
            at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
            at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
            at org.apache.spark.util.random.SamplingUtils$.reservoirSampleAndCount(SamplingUtils.scala:42)
            at org.apache.spark.RangePartitioner$$anonfun$8.apply(Partitioner.scala:259)
            at org.apache.spark.RangePartitioner$$anonfun$8.apply(Partitioner.scala:257)
            at org.apache.spark.rdd.RDD$$anonfun$15.apply(RDD.scala:647)
            at org.apache.spark.rdd.RDD$$anonfun$15.apply(RDD.scala:647)
            at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:35)
            at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:277)
            at org.apache.spark.rdd.RDD.iterator(RDD.scala:244)
            at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
            at org.apache.spark.scheduler.Task.run(Task.scala:64)
            at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:203)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
            at java.lang.Thread.run(Thread.java:745)

Looking at the code and the eval ParseRatingFn object reveals

    Long.valueOf(tokens[3])

However, it is hard to debug with tokens doesn't have 4 fields, as it should have (the given input has 4 fields as well).

**Comment by srowen** [comment]
Yeah that means something in the input does not have 4 fields. The input should all have 4 fields if you make it as in the example: `tr '\t' ',' < u.data > data.csv`  Is it possible other data was submitted to that topic, maybe from an old run? I agree, it's probably best to log the bad input in this case.

**Comment by srowen** [comment]
@moritzschaefer was the problem maybe that there was old data in a different format left over in the topic or on HDFS? I added changes to aid debugging by printing the offending line. If you're able to build and test a new build it might clarify the problem.

**Comment by moritzschaefer** [comment]
I checked the input data set (the csv) and didn't find any line with different than 4 fields. 
After that I created a CSV with only one line of input data with 4 fields to be very sure. Both times the same issue..

**Comment by srowen** [comment]
The problem is all but certainly previous input then, in the same topic or on HDFS. Have you sent other input in the past for a different problem to the same topic, or used the same HDFS directory for another instance? for example, can you delete/recreate the Kafka topic and use a new HDFS directory?

**Comment by moritzschaefer** [comment]
I deleted the topics and all data in the HDFS directory and now it doesn't complain anymore. Thanks

**Comment by srowen** [comment]
Great, well, I added some logging that would probably help debugging in this situation. Thanks for the report.
