### ISSUE TITLE
[2.1.0] Config file must be located in the same directory as oryx-run.sh

### ISSUE THREAD

**Issue by harscoet** [OryxProject/oryx#268]
Since 2.1.0, config file must be located in the same directory as oryx-run.sh

| Cmd                                                                      | State               |
|-----------------------------------------------------------|:--------------:|
| ./oryx-run.sh batch --conf oryx.conf                |  OK          |
|  ./oryx-run.sh batch --conf conf/oryx.conf      |  Config ignored   |
| ./oryx-run.sh batch --conf /etc/oryx/oryx.conf |  Config ignored   |

<img width="518" alt="capture d ecran 2015-12-04 a 12 09 57" src="https://cloud.githubusercontent.com/assets/2361402/11588346/fa569dc4-9a7f-11e5-9ddc-0d68224ef6c5.png">

**Comment by srowen** [comment]
Hm... I can't seem to reproduce that. I tried moving my config file to `/tmp` but it worked fine.

A config file is required but it defaults to `oryx.conf` if none is specified. It won't proceed if no config file is found, so clearly it's found something. You're sure it's not the config you expect -- I assume you're saying this output doesn't match what's in your config but can you double check?

It prints the `spark-submit` command. Have a look for parts like: `--conf spark.executor.extraJavaOptions="-Dconfig.file=example.conf"` and `--files /tmp/example.conf`. The latter should have the full path you specified. The former should just have the file name. Is that the case?

**Comment by harscoet** [comment]
I retried from scratch on debian and "Cloudera Express 5.5.0"
```sh
sudo mkdir -p /var/lib/oryx /var/log/oryx /etc/oryx
sudo useradd oryx --home-dir /var/lib/oryx
sudo adduser oryx sudo

sudo wget https://github.com/OryxProject/oryx/releases/download/oryx-2.1.0/compute-classpath.sh -P /var/lib/oryx
sudo wget https://github.com/OryxProject/oryx/releases/download/oryx-2.1.0/oryx-run.sh -P /var/lib/oryx
sudo wget https://github.com/OryxProject/oryx/releases/download/oryx-2.1.0/oryx-batch-2.1.0.jar -P /var/lib/oryx
sudo wget https://github.com/OryxProject/oryx/releases/download/oryx-2.1.0/oryx-serving-2.1.0.jar -P /var/lib/oryx
sudo wget https://github.com/OryxProject/oryx/releases/download/oryx-2.1.0/oryx-speed-2.1.0.jar -P /var/lib/oryx

sudo chmod +x /var/lib/oryx/oryx-run.sh /var/lib/oryx/compute-classpath.sh
sudo chown -R oryx:oryx /var/lib/oryx /var/log/oryx /etc/oryx

sudo su oryx
cd /var/lib/oryx
wget https://raw.githubusercontent.com/OryxProject/oryx/master/app/conf/als-example.conf -P /tmp

./oryx-run.sh batch --conf /tmp/als-example.conf
```
This is the output

```sh
spark-submit --master yarn-client --name OryxBatchLayer-ALSExample --class com.cloudera.oryx.batch.Main      --jars /opt/cloudera/parcels/CDH/jars/spark-examples-1.5.0-cdh5.5.0-hadoop2.6.0-cdh5.5.0.jar --files /tmp/als-example.conf --driver-memory 1g      --driver-java-options "-Dconfig.file=als-example.conf" --executor-memory 4g --executor-cores 8      --conf spark.executor.extraJavaOptions="-Dconfig.file=als-example.conf" --conf spark.ui.port=4040 --conf spark.io.compression.codec=lzf --conf spark.logConf=true --conf spark.serializer=org.apache.spark.serializer.KryoSerializer --conf spark.speculation=true --conf spark.ui.showConsoleProgress=false --num-executors=4 oryx-batch-2.1.0.jar
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/cloudera/parcels/CDH-5.5.0-1.cdh5.5.0.p0.8/jars/avro-tools-1.7.6-cdh5.5.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/cloudera/parcels/CDH-5.5.0-1.cdh5.5.0.p0.8/jars/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
15/12/04 14:51:12 INFO AbstractSparkLayer: Configuration:

    oryx {
        id=null
        "input-topic" {
            message {
                topic=OryxInput
                "key-decoder-class"="kafka.serializer.StringDecoder"
                "message-decoder-class"="kafka.serializer.StringDecoder"
                "message-class"="java.lang.String"
                "key-class"="java.lang.String"
            }
            lock {
                master="localhost:2181"
            }
            broker="localhost:9092"
        }
        "update-topic" {
            message {
                topic=OryxUpdate
                "encoder-class"="kafka.serializer.StringEncoder"
                "max-size"=16777216
                "decoder-class"="kafka.serializer.StringDecoder"
            }
            lock {
                master="localhost:2181"
            }
            broker="localhost:9092"
        }
        "default-streaming-config" {
            spark {
                ui {
                    showConsoleProgress=false
                }
                serializer="org.apache.spark.serializer.KryoSerializer"
                speculation=true
                logConf=true
                io {
                    compression {
                        codec=lzf
                    }
                }
            }
        }
        "input-schema" {
            "categorical-features"=null
            "numeric-features"=null
            "target-feature"=null
            "ignored-features"=[]
            "num-features"=0
            "feature-names"=[]
            "id-features"=[]
        }
        kmeans {
            hyperparams {
                k=10
            }
            iterations=30
            "initialization-strategy"="k-means||"
            runs=3
            "evaluation-strategy"=SILHOUETTE
        }
        speed {
            streaming {
                "num-executors"=2
                "executor-memory"="1g"
                "executor-cores"=4
                "driver-memory"="512m"
                config {
                    spark {
                        ui {
                            showConsoleProgress=false
                        }
                        serializer="org.apache.spark.serializer.KryoSerializer"
                        speculation=true
                        logConf=true
                        io {
                            compression {
                                codec=lzf
                            }
                        }
                    }
                }
                "generation-interval-sec"=10
                master="yarn-client"
                "dynamic-allocation"=false
            }
            ui {
                port=4040
            }
            "min-model-load-fraction"=0.8
            "model-manager-class"=null
        }
        batch {
            streaming {
                "num-executors"=4
                "executor-memory"="2g"
                "executor-cores"=4
                "driver-memory"="1g"
                config {
                    spark {
                        ui {
                            showConsoleProgress=false
                        }
                        serializer="org.apache.spark.serializer.KryoSerializer"
                        speculation=true
                        logConf=true
                        io {
                            compression {
                                codec=lzf
                            }
                        }
                    }
                }
                "generation-interval-sec"=21600
                master="yarn-client"
                "dynamic-allocation"=false
            }
            ui {
                port=4040
            }
            "update-class"=null
            storage {
                "model-dir"="file:/tmp/Oryx/model/"
                "key-writable-class"="org.apache.hadoop.io.Text"
                "message-writable-class"="org.apache.hadoop.io.Text"
                "data-dir"="file:/tmp/Oryx/data/"
            }
        }
        serving {
            "min-model-load-fraction"=0.8
            "application-resources"=null
            api {
                "user-name"=null
                port=80
                "read-only"=false
                "keystore-file"=null
                "context-path"="/"
                "keystore-password"=null
                "secure-port"=443
                password=*****
            }
            "no-init-topics"=false
            yarn {
                instances=1
                cores="4"
            }
            memory="4000m"
            "model-manager-class"=null
        }
        als {
            hyperparams {
                lambda=0.001
                alpha=1
                features=10
            }
            "sample-rate"=1
            "rescorer-provider-class"=null
            iterations=10
            implicit=true
            "no-known-items"=false
            decay {
                factor=1
                "zero-threshold"=0
            }
        }
        rdf {
            hyperparams {
                "max-depth"=8
                "min-node-size"=16
                "max-split-candidates"=100
                impurity=entropy
                "min-info-gain-nats"=0.001
            }
            "num-trees"=20
        }
        ml {
            eval {
                "test-fraction"=0.1
                parallelism=1
                candidates=1
            }
        }
    }

Exception in thread "main" com.typesafe.config.ConfigException$Null: reference.conf: 126: Configuration key 'oryx.batch.update-class' is set to null but expected STRING
	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:121)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:136)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:142)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:142)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:150)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:155)
	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:197)
	at com.cloudera.oryx.lambda.batch.BatchLayer.<init>(BatchLayer.java:58)
	at com.cloudera.oryx.batch.Main.main(Main.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:672)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by srowen** [comment]
Thanks @harscoet I see the error now. Are you able to try the patched version here to see if it works? It worked for me, once I got the reproduction right. I had to remove my local copy of the file!

**Comment by harscoet** [comment]
It works :+1: Thanks !
