### ISSUE TITLE
Spark 1.5 and JPMML: NoSuchMethodError org.dmg.pmml.Timestamp.addContent

### ISSUE THREAD

**Issue by srowen** [OryxProject/oryx#270]
Looks like this is a new problem in Spark 1.5, since it now uses JPMML heavily, but uses 1.1.x instead of the 1.2.x in this app. There are some workarounds, but the best one is probably shading JPMML in Oryx.

```
Exception in thread "streaming-job-executor-0"
java.lang.NoSuchMethodError: org.dmg.pmml.Timestamp.addContent([Ljava/lang/Object;)Lorg/dmg/pmml/Timestamp;
        at com.cloudera.oryx.common.pmml.PMMLUtils.buildSkeletonPMML(PMMLUtils.java:54)
        at com.cloudera.oryx.app.batch.mllib.als.ALSUpdate.mfModelToPMML(ALSUpdate.java:428)
        at com.cloudera.oryx.app.batch.mllib.als.ALSUpdate.buildModel(ALSUpdate.java:135)
        at com.cloudera.oryx.ml.MLUpdate$BuildAndEvalWorker.call(MLUpdate.java:359)
...
```

**Comment by harscoet** [comment]
:+1:
