### ISSUE TITLE
./oryx-run.sh batch SparkContext has been shutdown

### ISSUE THREAD

**Issue by pinguo-xudianyang** [OryxProject/oryx#285]
I trying the ALS Example，But ./oryx-run.sh batch Error running job streaming job.

My Hadoop cluster running the following components by CDH-5.5.1:
    Apache Hadoop 2.6.0 or later
    Apache Zookeeper 3.4.5 or later
    Apache Kafka 0.8.2 or later (in 0.8.x line)
    Apache Spark 1.5.0 or later

Console Error Log:

16/04/16 01:55:00 INFO VerifiableProperties: Verifying properties
16/04/16 01:55:00 INFO VerifiableProperties: Property auto.offset.reset is overridden to largest
16/04/16 01:55:00 INFO VerifiableProperties: Property group.id is overridden to OryxGroup-BatchLayer-ALSExample
16/04/16 01:55:00 INFO VerifiableProperties: Property zookeeper.connect is overridden to 
16/04/16 01:55:00 INFO JobScheduler: Added jobs for time 1460742900000 ms
16/04/16 01:55:00 INFO JobScheduler: Starting job streaming job 1460742900000 ms.0 from job set of time 1460742900000 ms
16/04/16 01:55:00 INFO JobScheduler: Starting job streaming job 1460742900000 ms.1 from job set of time 1460742900000 ms
16/04/16 01:55:00 ERROR JobScheduler: Error running job streaming job 1460742900000 ms.0
java.lang.IllegalStateException: SparkContext has been shutdown
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1816)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1837)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:1850)
        at org.apache.spark.rdd.RDD$$anonfun$take$1.apply(RDD.scala:1298)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
        at org.apache.spark.rdd.RDD.take(RDD.scala:1272)
        at org.apache.spark.rdd.RDD$$anonfun$isEmpty$1.apply$mcZ$sp(RDD.scala:1399)
        at org.apache.spark.rdd.RDD$$anonfun$isEmpty$1.apply(RDD.scala:1399)
        at org.apache.spark.rdd.RDD$$anonfun$isEmpty$1.apply(RDD.scala:1399)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
        at org.apache.spark.rdd.RDD.isEmpty(RDD.scala:1398)
        at org.apache.spark.api.java.JavaRDDLike$class.isEmpty(JavaRDDLike.scala:516)
        at org.apache.spark.api.java.AbstractJavaRDDLike.isEmpty(JavaRDDLike.scala:47)
        at com.cloudera.oryx.lambda.batch.BatchUpdateFunction.call(BatchUpdateFunction.java:90)
        at com.cloudera.oryx.lambda.batch.BatchUpdateFunction.call(BatchUpdateFunction.java:50)
        at org.apache.spark.streaming.api.java.JavaDStreamLike$$anonfun$foreachRDD$2.apply(JavaDStreamLike.scala:323)
        at org.apache.spark.streaming.api.java.JavaDStreamLike$$anonfun$foreachRDD$2.apply(JavaDStreamLike.scala:323)
        at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ForEachDStream.scala:42)
        at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ForEachDStream.scala:40)
        at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ForEachDStream.scala:40)
        at org.apache.spark.streaming.dstream.DStream.createRDDWithLocalProperties(DStream.scala:399)
        at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply$mcV$sp(ForEachDStream.scala:40)
        at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:40)
        at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:40)
        at scala.util.Try$.apply(Try.scala:161)
        at org.apache.spark.streaming.scheduler.Job.run(Job.scala:34)
        at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply$mcV$sp(JobScheduler.scala:207)
        at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply(JobScheduler.scala:207)
        at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply(JobScheduler.scala:207)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
        at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler.run(JobScheduler.scala:206)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by srowen** [comment]
You are running Oryx 2.1? This error really means something else went wrong earlier. Do you have more logs showing another error?

**Comment by pinguo-xudianyang** [comment]
yes, I'm running Oryx 2.1.2，the list:
compute-classpath.sh oryx-batch-2.1.2.jar  oryx.conf  oryx-run.sh  oryx-serving-2.1.2.jar  oryx-speed-2.1.2.jar

I collect all running log until an error has occured abouve.

stdout and stderr log file:[oryx_batch.log](http://a.phpboy.net/oryx_batch)
oryx.conf:[oryx.conf](http://a.phpboy.net/oryx)

**Comment by srowen** [comment]
It looks like your various processes can't communicate:

```
16/04/16 10:19:34 WARN YarnSchedulerBackend$YarnSchedulerEndpoint: ApplicationMaster has disassociated: 192.168.60.225:6113
16/04/16 10:19:34 WARN YarnSchedulerBackend$YarnSchedulerEndpoint: ApplicationMaster has disassociated: 192.168.60.225:6113
16/04/16 10:19:34 ERROR ErrorMonitor: AssociationError [akka.tcp://sparkDriver@192.168.60.226:7284] -> [akka.tcp://sparkYarnAM@192.168.60.225:6113]: Error [Association failed with [akka.tcp://sparkYarnAM@192.168.60.225:6113]] [
akka.remote.EndpointAssociationException: Association failed with [akka.tcp://sparkYarnAM@192.168.60.225:6113]
Caused by: akka.remote.transport.netty.NettyTransport$$anonfun$associate$1$$anon$2: Connection refused: /192.168.60.225:6113
]
```

Check your network / firewall config on these nodes. Make sure you mean 192.168.* since this is a local non-routeable IP address.

**Comment by pinguo-xudianyang** [comment]
batch {
    streaming {
      generation-interval-sec = 30
      num-executors = 4
      c
      executor-memory = "1g"
    }

My test env machines have 6 cores, but default oryx.conf executor-cores=8, change to 4, everything is ok.
