### ISSUE TITLE
./oryx-run.sh serving Caused by: java.lang.ClassNotFoundException: kafka.serializer.Decoder

### ISSUE THREAD

**Issue by dengshilong** [OryxProject/oryx#287]
I find https://github.com/OryxProject/oryx/issues/283 is the same problem. I don't understand "That means you don't have Kafka classes available in the usual place on your CDH cluster. Did you install the parcel and set up the topics per the docs?", because I have not used CDH cluster, I just download Hadoop from http://www.apache.org/dyn/closer.cgi/hadoop/common/hadoop-2.7.2/hadoop-2.7.2.tar.gz, and start Hadoop in  pseudo-distributed mode. After run `./oryx-run.sh serving`, it print out 
```
java.lang.NoClassDefFoundError: kafka/serializer/Decoder
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
        at java.lang.Class.getConstructor0(Class.java:3075)
        at java.lang.Class.newInstance(Class.java:412)
        at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:121)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4734)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: kafka.serializer.Decoder
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 14 more
```

**Comment by srowen** [comment]
You can comment on that issue instead of making a new issue. In fact this is more of a question, which ought to go to https://groups.google.com/a/cloudera.org/forum/#!forum/oryx-user

It will not work out of the box unless you're using CDH, since the scripts are set up to expect jars in certain locations. It should be quite simple to modify the `compute-classpath.sh` script for your cluster but you'd have to do that. There are no dependencies on CDH per se other than configuration of where jars are.

**Comment by srowen** [comment]
I should say that if you get this working and have a clean classpath script for plain Apache Hadoop and Kafka clusters, you can reopen this and I can work with you to add it.

**Comment by dengshilong** [comment]
I just add Kafka libs and run java command direct for test,
java -Djava.ext.dirs=/Users/long/software/kafka_2.10-0.8.2.2/libs -Dconfig.file=oryx.conf -jar oryx-serving-2.1.2.jar com.cloudera.oryx.serving.Main.

**Comment by srowen** [comment]
It doesn't quite work that way. You need to modify compute-classpath.sh and use oryx-run.sh.

**Comment by dengshilong** [comment]
I still can't find a good way to modify compute-classpath.sh. So I just add --ext-dirs parameter in oryx-run.sh.

**Comment by littlecong** [comment]
My CDH is setup using packages. 
This is my compute-classpath.sh, and it works for me

function printLatest() {
  ls -1 $2/$1 2>/dev/null | grep -vE "tests.jar$" | tail -1
}

# For Spark-based batch and speed layer, the only thing that needs to be supplied, really,
# are the Kafka libraries that the cluster uses. The Spark Examples jar happens to ship this
# and is maybe both easier to find and more harmonized than a stand-alone Kafka distro on
# the cluster, but this is a hacky way to acquire it
printLatest "spark-examples-*.jar" "/usr/lib/spark/lib"

# The remaining dependencies support the Serving Layer, which needs Hadoop, Kafka,
# and ZK dependencies
printLatest "spark-assembly-*.jar" "/usr/lib/spark/lib"
printLatest "zookeeper-*.jar" "/usr/lib/zookeeper"
printLatest "hadoop-auth-*.jar" "/usr/lib/hadoop"
printLatest "hadoop-common-*.jar" "/usr/lib/hadoop"
printLatest "hadoop-hdfs-2*.jar" "/usr/lib/hadoop-hdfs"
printLatest "htrace-core4-*.jar" "/usr/lib/hadoop/lib"
printLatest "commons-cli-1*.jar" "/usr/lib/hadoop/lib"
printLatest "commons-collections-*.jar" "/usr/lib/hadoop/lib" 
printLatest "commons-configuration-*.jar" "/usr/lib/hadoop/lib"
printLatest "protobuf-java-2.5*.jar" "/usr/lib/hadoop/lib"
printLatest "snappy-java-*.jar" "/usr/lib/hadoop/lib"
printLatest "kafka_2.11-0.9.0-kafka-2.0.2.jar" "/usr/lib/kafka/libs"

# These are needed for submitting the serving layer in YARN mode
printLatest "hadoop-yarn-applications-distributedshell-*.jar" "/usr/lib/hadoop-yarn"
