### ISSUE TITLE
Could oryx2 run on hdp?

### ISSUE THREAD

**Issue by gaoxuesong** [OryxProject/oryx#292]
Could oryx 2.2.0 run on hdp (Hortonworks data platform)?
My Hadoop cluster is based on hdp (Hortonworks data platform). So I want to know whether oryx 2 support hdp2.4? The hdp2.4 support Spark 1.6 and Hadoop 2.0+.

When I run oryx-run.sh on hdp, it display:

**`[root@sandbox release]# sh oryx-run.sh kafka-setup --conf /root/oryx2/release/oryx.conf`**

Exception in thread "main" java.lang.UnsupportedClassVersionError: com/cloudera/oryx/common/settings/ConfigToProperties : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
Config file /root/oryx2/release/oryx.conf could not be parsed
usage: oryx-run.sh command [--option value] ...
  where command is one of:
    batch        Run Batch Layer
    speed        Run Speed Layer
    serving      Run Serving Layer
    kafka-setup  Inspect ZK/Kafka config and configure Kafka topics
    kafka-tail   Follow output from Kafka topics
    kafka-input  Push data to input topic
  and options are one of:
    --layer-jar  Oryx JAR file, like oryx-{serving,speed,batch}-x.y.z.jar
                 Defaults to any oryx-*.jar in working dir
    --conf       Oryx configuration file, like oryx.conf. Defaults to 'oryx.conf'
    --app-jar    User app JAR file
    --jvm-args   Extra args to Oryx JVM processes (including drivers and executors)
    --deployment Only for Serving Layer now; can be 'yarn' or 'local', Default: local.
    --input-file Only for kafka-input. Input file to send
    --help       Display this message

**Comment by srowen** [comment]
This was repeated at https://groups.google.com/a/cloudera.org/forum/#!forum/oryx-user so I will answer there.
