### ISSUE TITLE
mvn install error

### ISSUE THREAD

**Issue by djKooks** [OryxProject/oryx#348]
Hello
I tried `mvn install` before to running word count example, but found error like:
```
2018-08-16 15:50:27,702 WARN  RequestSendThread:91 [Controller-5-to-broker-5-send-thread]: Controller 5 epoch 1 fails to send request (type: UpdateMetadataRequest=, controllerId=5, controllerEpoch=1, partitionStates={}, liveBrokers=(id=5, endPoints=(host=lm-macbook-53, port=55619, listenerName=ListenerName(PLAINTEXT), securityProtocol=PLAINTEXT), rack=null)) to broker lm-macbook-53:55619 (id: 5 rack: null). Reconnecting to broker.
java.io.IOException: Connection to 5 was disconnected before the response was read
	at org.apache.kafka.clients.NetworkClientUtils.sendAndReceive(NetworkClientUtils.java:93)
	at kafka.controller.RequestSendThread.doWork(ControllerChannelManager.scala:225)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:64)
2018-08-16 15:50:27,751 WARN  NetworkClient:846 Error while fetching metadata with correlation id 281 : {ProduceConsumeITTopic=LEADER_NOT_AVAILABLE}
2018-08-16 15:50:27,755 WARN  NetworkClient:846 Error while fetching metadata with correlation id 280 : {ProduceConsumeITTopic=LEADER_NOT_AVAILABLE}
2018-08-16 15:50:27,858 WARN  NetworkClient:846 Error while fetching metadata with correlation id 282 : {ProduceConsumeITTopic=LEADER_NOT_AVAILABLE}
2018-08-16 15:50:27,862 WARN  NetworkClient:846 Error while fetching metadata with correlation id 281 : {ProduceConsumeITTopic=LEADER_NOT_AVAILABLE}
2018-08-16 15:50:27,962 WARN  NetworkClient:846 Error while fetching metadata with correlation id 283 : {ProduceConsumeITTopic=LEADER_NOT_AVAILABLE}
2018-08-16 15:50:27,965 WARN  NetworkClient:846 Error while fetching metadata with correlation id 282 : {ProduceConsumeITTopic=LEADER_NOT_AVAILABLE}
2018-08-16 15:50:28,067 WARN  NetworkClient:846 Error while fetching
...
```
Do I have to do something?

**Comment by srowen** [comment]
Hm, `mvn install` works for me and works on Travis. Any earlier failures? what are you building? You can use `-DskipTests` to just not run the tests.
