### ISSUE TITLE
Explain / fix non-fatal exceptions during integration tests

### ISSUE THREAD

**Issue by srowen** [OryxProject/oryx#73]
There are several types of exceptions that appear regularly in the logs when integration tests run. They do not appear to affect the result, and tests pass. They may just be corner cases, from ZK and Kafka being rapidly started and stopped. This is a to-do to see if we can ever figure them out.

Updated to include what's being observed most recently. It's almost all:

```
java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:470)
	at kafka.api.TopicDataSend.writeTo(FetchResponse.scala:123)
	at kafka.network.MultiSend.writeTo(Transmission.scala:101)
	at kafka.api.FetchResponseSend.writeTo(FetchResponse.scala:231)
	at kafka.network.Processor.write(SocketServer.scala:472)
	at kafka.network.Processor.run(SocketServer.scala:342)
	at java.lang.Thread.run(Thread.java:745)
```

Rarely:

```
java.nio.channels.ClosedByInterruptException
	at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
	at sun.nio.ch.SocketChannelImpl.poll(SocketChannelImpl.java:956)
	at sun.nio.ch.SocketAdaptor$SocketInputStream.read(SocketAdaptor.java:204)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
	at java.nio.channels.Channels$ReadableByteChannelImpl.read(Channels.java:385)
	at kafka.utils.Utils$.read(Utils.scala:380)
	at kafka.network.BoundedByteBufferReceive.readFrom(BoundedByteBufferReceive.scala:54)
	at kafka.network.Receive$class.readCompletely(Transmission.scala:56)
	at kafka.network.BoundedByteBufferReceive.readCompletely(BoundedByteBufferReceive.scala:29)
	at kafka.network.BlockingChannel.receive(BlockingChannel.scala:111)
	at kafka.producer.SyncProducer.liftedTree1$1(SyncProducer.scala:75)
	at kafka.producer.SyncProducer.kafka$producer$SyncProducer$$doSend(SyncProducer.scala:72)
	at kafka.producer.SyncProducer.send(SyncProducer.scala:113)
	at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:58)
	at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:93)
	at kafka.consumer.ConsumerFetcherManager$LeaderFinderThread.doWork(ConsumerFetcherManager.scala:66)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:60)
```

and a few in the web tests:

```
java.lang.IllegalStateException: ServiceLocatorImpl(__HK2_Generated_73,74,527137253) has been shut down
	at org.glassfish.grizzly.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:151)
	at org.glassfish.grizzly.servlet.FilterChainImpl.invokeFilterChain(FilterChainImpl.java:106)
	at org.glassfish.grizzly.servlet.ServletHandler.doServletService(ServletHandler.java:221)
	at org.glassfish.grizzly.servlet.ServletHandler.service(ServletHandler.java:169)
	at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:219)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:565)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:545)
	at java.lang.Thread.run(Thread.java:745)
```

Others seem to have gone.

**Comment by srowen** [comment]
I'm closing this, not because it's completely resolved (although a number of these have seemingly been resolved) but because it doesn't seem to be a problem, and doesn't seem to be easily preventable in this context where these processes are being shut down rapidly but cleanly.
